modLoader="javafml" 

loaderVersion="[36,)" 

license="All rights reserved"

[[mods]] 

modId="nightsouls" 
version="1.0"
displayName="NightSouls Mod Requiem"

logoFile="icon.png" 

credits="Merci a Miizeal, Krahne et Basti_io !" 

authors="Mod cree par Saitaquack. Structures par Miizeal et Krahne."

description='''
Le mod NightSouls ajoute plus de 250 items, un paquet d'armes et d'armures, plein de nouvelles structures et 46 nouvelles musiques.
Attendez-vous a des references a Overwatch, Mario, JoJo, Terraria, le YouTube francais, RPZ, Undertale, FNAF et meme du ballermann...
Ce mod a ete adapte pour une partie des cites des sables. Amassez le plus de NightSouls Emeralds possibles et remportez la victoire !

IP : NIGHTSOULS.LOCATION-MINECRAFT.FR

4 anciennes legendes dominaient le monde il y'a longtemps. Recuperez leurs pouvoirs et dominez vos adversaires.
'''


[[dependencies.examplemod]]

    modId="forge" #mandatory

    mandatory=true #mandatory

    versionRange="[36,)" #mandatory

    ordering="NONE"

    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
